###
POST http://127.0.0.1:8083/auth/login
Content-Type: application/json

{
    "email": "superuser@exampl.com",
    "password": "Tr0j4n_w4r3"
}

###
POST http://127.0.0.1:8083/users

###
GET http://127.0.0.1:8083